title: Kotlin for Beginners
description: >- 
  A documentation of the programming language Kotlin.
baseurl: "/kotlin-for-beginners" 
url: "" 
twitter_username: meikellp
github_username:  meikellp

# Build settings
markdown: kramdown
plugins:
  - jekyll-relative-links

category-list: ["Language Features", "Java & Kotlin"]

sass:
  sass_dir: assets

include:
- assets/main.sass

exclude:
- "Gemfile"
- "Gemfile.lock"
- ".gitignore"
- "package-lock.json"
- "package.json"
- "node_modules/"

defaults:
  -
    values:
      layout: "doc"
