title: Kotlin for Beginners
description: >- 
  A documentation of the programming language Kotlin.
baseurl: "/kotlin-for-beginners" 
url: "" 
twitter_username: meikellp
github_username:  meikellp

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-relative-links
